name: Atualizar CSV Pedidos

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug leitura dos secrets
        run: |
          echo "VTEX_ACCOUNT_NAME = '$VTEX_ACCOUNT_NAME'"
          echo "VTEX_APP_KEY length = ${#VTEX_APP_KEY}"
          echo "VTEX_APP_TOKEN length = ${#VTEX_APP_TOKEN}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Rodar script Itens VTEX
        run: python src/pedidos_itens.py

      - name: Rodar script Geral VTEX
        run: python src/pedidos_gerais.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/*.csv
          git commit -m "Atualiza CSVs VTEX" || echo "Sem alterações"
          git push
